language: cpp

sudo: required

services:
  - docker

compiler:
  - gcc

script:
  - docker pull hobywan/cosyr:latest
  - docker run -v "$(pwd):/home/cosyr" -it hobywan/cosyr /bin/bash -c
            "cd /home/cosyr && mkdir build && cd build && \
            cmake -Wno-dev \
              -DCMAKE_BUILD_TYPE=Release \
              -DENABLE_TCMALLOC=False \
              -DPORTAGE_DIR=/home/dependencies/portage \
              -DKokkos_DIR=/home/dependencies/kokkos \
              -Dpybind11_DIR=/home/dependencies/pybind \
              -DCabana_DIR=/home/dependencies/cabana \
              .. && \
            make -j 4"